// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package notification_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//QueueRequest for Queue Request with these defined requirements
type MessageOut struct {
	NotificationID       string            `protobuf:"bytes,2,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	ProfileID            string            `protobuf:"bytes,3,opt,name=profileID,proto3" json:"profileID,omitempty"`
	ContactID            string            `protobuf:"bytes,4,opt,name=contactID,proto3" json:"contactID,omitempty"`
	SubscriptionID       string            `protobuf:"bytes,5,opt,name=subscriptionID,proto3" json:"subscriptionID,omitempty"`
	MessageTemplete      string            `protobuf:"bytes,6,opt,name=messageTemplete,proto3" json:"messageTemplete,omitempty"`
	MessageVariables     map[string]string `protobuf:"bytes,7,rep,name=messageVariables,proto3" json:"messageVariables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Language             string            `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Autosend             bool              `protobuf:"varint,9,opt,name=autosend,proto3" json:"autosend,omitempty"`
	Channel              string            `protobuf:"bytes,10,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MessageOut) Reset()         { *m = MessageOut{} }
func (m *MessageOut) String() string { return proto.CompactTextString(m) }
func (*MessageOut) ProtoMessage()    {}
func (*MessageOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *MessageOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOut.Unmarshal(m, b)
}
func (m *MessageOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOut.Marshal(b, m, deterministic)
}
func (m *MessageOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOut.Merge(m, src)
}
func (m *MessageOut) XXX_Size() int {
	return xxx_messageInfo_MessageOut.Size(m)
}
func (m *MessageOut) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOut.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOut proto.InternalMessageInfo

func (m *MessageOut) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *MessageOut) GetProfileID() string {
	if m != nil {
		return m.ProfileID
	}
	return ""
}

func (m *MessageOut) GetContactID() string {
	if m != nil {
		return m.ContactID
	}
	return ""
}

func (m *MessageOut) GetSubscriptionID() string {
	if m != nil {
		return m.SubscriptionID
	}
	return ""
}

func (m *MessageOut) GetMessageTemplete() string {
	if m != nil {
		return m.MessageTemplete
	}
	return ""
}

func (m *MessageOut) GetMessageVariables() map[string]string {
	if m != nil {
		return m.MessageVariables
	}
	return nil
}

func (m *MessageOut) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *MessageOut) GetAutosend() bool {
	if m != nil {
		return m.Autosend
	}
	return false
}

func (m *MessageOut) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type StatusRequest struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

type StatusResponse struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Released             bool     `protobuf:"varint,3,opt,name=released,proto3" json:"released,omitempty"`
	TransientID          string   `protobuf:"bytes,4,opt,name=transientID,proto3" json:"transientID,omitempty"`
	ExternalID           string   `protobuf:"bytes,5,opt,name=externalID,proto3" json:"externalID,omitempty"`
	ExternalStatus       string   `protobuf:"bytes,6,opt,name=externalStatus,proto3" json:"externalStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *StatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StatusResponse) GetReleased() bool {
	if m != nil {
		return m.Released
	}
	return false
}

func (m *StatusResponse) GetTransientID() string {
	if m != nil {
		return m.TransientID
	}
	return ""
}

func (m *StatusResponse) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

func (m *StatusResponse) GetExternalStatus() string {
	if m != nil {
		return m.ExternalStatus
	}
	return ""
}

type ReleaseRequest struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	ReleaseMessage       string   `protobuf:"bytes,2,opt,name=releaseMessage,proto3" json:"releaseMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseRequest) Reset()         { *m = ReleaseRequest{} }
func (m *ReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*ReleaseRequest) ProtoMessage()    {}
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *ReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseRequest.Unmarshal(m, b)
}
func (m *ReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseRequest.Marshal(b, m, deterministic)
}
func (m *ReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseRequest.Merge(m, src)
}
func (m *ReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_ReleaseRequest.Size(m)
}
func (m *ReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseRequest proto.InternalMessageInfo

func (m *ReleaseRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *ReleaseRequest) GetReleaseMessage() string {
	if m != nil {
		return m.ReleaseMessage
	}
	return ""
}

type MessageIn struct {
	NotificationID       string            `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	Contact              string            `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	ProductID            string            `protobuf:"bytes,3,opt,name=productID,proto3" json:"productID,omitempty"`
	ChannelID            string            `protobuf:"bytes,4,opt,name=channelID,proto3" json:"channelID,omitempty"`
	MessageType          string            `protobuf:"bytes,5,opt,name=messageType,proto3" json:"messageType,omitempty"`
	PayLoad              map[string]string `protobuf:"bytes,6,rep,name=payLoad,proto3" json:"payLoad,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Language             string            `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MessageIn) Reset()         { *m = MessageIn{} }
func (m *MessageIn) String() string { return proto.CompactTextString(m) }
func (*MessageIn) ProtoMessage()    {}
func (*MessageIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4}
}

func (m *MessageIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageIn.Unmarshal(m, b)
}
func (m *MessageIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageIn.Marshal(b, m, deterministic)
}
func (m *MessageIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageIn.Merge(m, src)
}
func (m *MessageIn) XXX_Size() int {
	return xxx_messageInfo_MessageIn.Size(m)
}
func (m *MessageIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageIn.DiscardUnknown(m)
}

var xxx_messageInfo_MessageIn proto.InternalMessageInfo

func (m *MessageIn) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *MessageIn) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *MessageIn) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *MessageIn) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *MessageIn) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *MessageIn) GetPayLoad() map[string]string {
	if m != nil {
		return m.PayLoad
	}
	return nil
}

func (m *MessageIn) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type SearchRequest struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Contact              string   `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{5}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *SearchRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *SearchRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *SearchRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SearchResponse struct {
	NotificationID       string            `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	ProfileID            string            `protobuf:"bytes,2,opt,name=profileID,proto3" json:"profileID,omitempty"`
	ContactID            string            `protobuf:"bytes,3,opt,name=contactID,proto3" json:"contactID,omitempty"`
	ProductID            string            `protobuf:"bytes,4,opt,name=productID,proto3" json:"productID,omitempty"`
	SubscriptionID       string            `protobuf:"bytes,5,opt,name=subscriptionID,proto3" json:"subscriptionID,omitempty"`
	Language             string            `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	MessageType          string            `protobuf:"bytes,7,opt,name=messageType,proto3" json:"messageType,omitempty"`
	PayLoad              map[string]string `protobuf:"bytes,8,rep,name=payLoad,proto3" json:"payLoad,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Outbound             bool              `protobuf:"varint,9,opt,name=outbound,proto3" json:"outbound,omitempty"`
	State                string            `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Released             bool              `protobuf:"varint,11,opt,name=released,proto3" json:"released,omitempty"`
	TransientID          string            `protobuf:"bytes,12,opt,name=transientID,proto3" json:"transientID,omitempty"`
	ExternalID           string            `protobuf:"bytes,13,opt,name=externalID,proto3" json:"externalID,omitempty"`
	ExternalStatus       string            `protobuf:"bytes,14,opt,name=externalStatus,proto3" json:"externalStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *SearchResponse) GetProfileID() string {
	if m != nil {
		return m.ProfileID
	}
	return ""
}

func (m *SearchResponse) GetContactID() string {
	if m != nil {
		return m.ContactID
	}
	return ""
}

func (m *SearchResponse) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *SearchResponse) GetSubscriptionID() string {
	if m != nil {
		return m.SubscriptionID
	}
	return ""
}

func (m *SearchResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SearchResponse) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *SearchResponse) GetPayLoad() map[string]string {
	if m != nil {
		return m.PayLoad
	}
	return nil
}

func (m *SearchResponse) GetOutbound() bool {
	if m != nil {
		return m.Outbound
	}
	return false
}

func (m *SearchResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SearchResponse) GetReleased() bool {
	if m != nil {
		return m.Released
	}
	return false
}

func (m *SearchResponse) GetTransientID() string {
	if m != nil {
		return m.TransientID
	}
	return ""
}

func (m *SearchResponse) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

func (m *SearchResponse) GetExternalStatus() string {
	if m != nil {
		return m.ExternalStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageOut)(nil), "notification.MessageOut")
	proto.RegisterMapType((map[string]string)(nil), "notification.MessageOut.MessageVariablesEntry")
	proto.RegisterType((*StatusRequest)(nil), "notification.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "notification.StatusResponse")
	proto.RegisterType((*ReleaseRequest)(nil), "notification.ReleaseRequest")
	proto.RegisterType((*MessageIn)(nil), "notification.MessageIn")
	proto.RegisterMapType((map[string]string)(nil), "notification.MessageIn.PayLoadEntry")
	proto.RegisterType((*SearchRequest)(nil), "notification.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "notification.SearchResponse")
	proto.RegisterMapType((map[string]string)(nil), "notification.SearchResponse.PayLoadEntry")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07) }

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0x13, 0x3b,
	0x14, 0xd6, 0x64, 0xd2, 0x4c, 0x72, 0xda, 0xe6, 0x56, 0xbe, 0xf7, 0xea, 0x5a, 0xb9, 0x15, 0x8a,
	0x22, 0x84, 0xc2, 0x26, 0x42, 0x65, 0x01, 0x2a, 0x82, 0x05, 0x6d, 0x17, 0x91, 0xf8, 0x53, 0x8a,
	0x58, 0x74, 0x85, 0x33, 0x39, 0x6d, 0x47, 0x4c, 0x3d, 0xc3, 0xd8, 0x53, 0x91, 0x15, 0xcf, 0xc4,
	0x82, 0x27, 0xe0, 0x15, 0x78, 0x04, 0x1e, 0x04, 0x8d, 0xed, 0xf9, 0xf1, 0x24, 0x69, 0x12, 0xb1,
	0xf3, 0xf9, 0x7c, 0x6c, 0x9f, 0x7c, 0xe7, 0x3b, 0x5f, 0x06, 0x08, 0x8f, 0x64, 0x70, 0x19, 0xf8,
	0x4c, 0x06, 0x11, 0x1f, 0xc5, 0x49, 0x24, 0x23, 0xb2, 0x57, 0xc5, 0x06, 0xdf, 0x5d, 0x80, 0xd7,
	0x28, 0x04, 0xbb, 0xc2, 0xb7, 0xa9, 0x24, 0x0f, 0xa0, 0x5b, 0xdd, 0x1e, 0x9f, 0xd2, 0x46, 0xdf,
	0x19, 0x76, 0x26, 0x35, 0x94, 0x1c, 0x42, 0x27, 0x4e, 0xa2, 0xcb, 0x20, 0xc4, 0xf1, 0x29, 0x75,
	0x55, 0x4a, 0x09, 0x64, 0xbb, 0x7e, 0xc4, 0x25, 0xf3, 0xe5, 0xf8, 0x94, 0x36, 0xf5, 0x6e, 0x01,
	0x64, 0x6f, 0x88, 0x74, 0x2a, 0xfc, 0x24, 0x88, 0xcd, 0x1b, 0x3b, 0xfa, 0x0d, 0x1b, 0x25, 0x43,
	0xf8, 0xeb, 0x46, 0x57, 0xf6, 0x1e, 0x6f, 0xe2, 0x10, 0x25, 0xd2, 0x96, 0x4a, 0xac, 0xc3, 0xe4,
	0x02, 0x0e, 0x0c, 0xf4, 0x81, 0x25, 0x01, 0x9b, 0x86, 0x28, 0xa8, 0xd7, 0x77, 0x87, 0xbb, 0x47,
	0xa3, 0x91, 0xc5, 0x40, 0xf9, 0x4b, 0xf3, 0x65, 0x71, 0xe0, 0x8c, 0xcb, 0x64, 0x3e, 0x59, 0xb8,
	0x87, 0xf4, 0xa0, 0x1d, 0x32, 0x7e, 0x95, 0xb2, 0x2b, 0xa4, 0x6d, 0xf5, 0x7c, 0x11, 0x67, 0x7b,
	0x2c, 0x95, 0x91, 0x40, 0x3e, 0xa3, 0x9d, 0xbe, 0x33, 0x6c, 0x4f, 0x8a, 0x98, 0x50, 0xf0, 0xfc,
	0x6b, 0xc6, 0x39, 0x86, 0x14, 0xd4, 0xb1, 0x3c, 0xec, 0x9d, 0xc0, 0xbf, 0x4b, 0x1f, 0x27, 0x07,
	0xe0, 0x7e, 0xc2, 0x39, 0x75, 0x54, 0x7a, 0xb6, 0x24, 0xff, 0xc0, 0xce, 0x2d, 0x0b, 0x53, 0x34,
	0x5d, 0xd0, 0xc1, 0x71, 0xe3, 0xa9, 0x33, 0x78, 0x02, 0xfb, 0xe7, 0x92, 0xc9, 0x54, 0x4c, 0xf0,
	0x73, 0x8a, 0x62, 0x59, 0xe7, 0x9c, 0x65, 0x9d, 0x1b, 0xfc, 0x74, 0xa0, 0x9b, 0x9f, 0x14, 0x71,
	0xc4, 0x05, 0x6e, 0x7a, 0x34, 0xab, 0x46, 0x48, 0x26, 0x8b, 0x6a, 0x54, 0x90, 0x91, 0x90, 0x60,
	0x88, 0x4c, 0xe0, 0x4c, 0x29, 0xa1, 0x3d, 0x29, 0x62, 0xd2, 0x87, 0x5d, 0x99, 0x30, 0x2e, 0x02,
	0xe4, 0xa5, 0x14, 0xaa, 0x10, 0xb9, 0x07, 0x80, 0x5f, 0x24, 0x26, 0x9c, 0x85, 0x85, 0x10, 0x2a,
	0x48, 0x56, 0x5b, 0x1e, 0xe9, 0xaa, 0x8d, 0x06, 0x6a, 0xe8, 0xe0, 0x23, 0x74, 0x27, 0xfa, 0xd5,
	0x2d, 0x09, 0xc9, 0xf2, 0x4c, 0xbd, 0xa6, 0x2b, 0xb9, 0xe4, 0x6d, 0x74, 0xf0, 0xa3, 0x01, 0x1d,
	0xb3, 0x1e, 0xf3, 0x8d, 0x6f, 0xcf, 0x64, 0xa0, 0x95, 0x6f, 0xae, 0xcd, 0x43, 0x33, 0x42, 0xb3,
	0x54, 0x0d, 0x49, 0x39, 0x42, 0x1a, 0x50, 0x23, 0xa4, 0xf5, 0x52, 0x19, 0xa1, 0x1c, 0xc8, 0x78,
	0xcd, 0x67, 0x60, 0x1e, 0xa3, 0xa1, 0xad, 0x0a, 0x91, 0x17, 0xe0, 0xc5, 0x6c, 0xfe, 0x2a, 0x62,
	0x33, 0xda, 0x52, 0x93, 0x70, 0x7f, 0xe9, 0x24, 0x8c, 0xf9, 0xe8, 0x9d, 0x4e, 0xd3, 0xfa, 0xcf,
	0x0f, 0x59, 0xb2, 0xf7, 0x6c, 0xd9, 0xf7, 0x8e, 0x61, 0xaf, 0x7a, 0x68, 0x2b, 0xdd, 0x7e, 0x85,
	0xfd, 0x73, 0x64, 0x89, 0x7f, 0xbd, 0x6d, 0x9b, 0x08, 0x34, 0x67, 0xa5, 0xf6, 0xd4, 0xba, 0x4a,
	0xae, 0x6b, 0x93, 0x4b, 0xc1, 0x33, 0x6c, 0x18, 0xf2, 0xf2, 0x70, 0xf0, 0xad, 0x09, 0xdd, 0xbc,
	0x82, 0x2d, 0xf5, 0x6f, 0x99, 0x5e, 0xe3, 0x4e, 0xd3, 0x73, 0xeb, 0xa6, 0x67, 0x75, 0xbb, 0x59,
	0xef, 0xf6, 0xa6, 0x96, 0x58, 0xed, 0x4a, 0xab, 0x66, 0x46, 0x35, 0x4d, 0x78, 0x8b, 0x9a, 0x38,
	0x29, 0x35, 0xd1, 0x56, 0x9a, 0x78, 0x68, 0x6b, 0xc2, 0xa6, 0x65, 0xb5, 0x30, 0xa2, 0x54, 0x4e,
	0xa3, 0xb4, 0xf4, 0xbc, 0x3c, 0x2e, 0x0d, 0x02, 0x56, 0x19, 0xc4, 0xee, 0xdd, 0x06, 0xb1, 0xb7,
	0xce, 0x20, 0xf6, 0x37, 0x30, 0x88, 0xee, 0x32, 0x83, 0xf8, 0x13, 0xd1, 0x1e, 0xfd, 0x6a, 0xc0,
	0xdf, 0x6f, 0x2a, 0x4c, 0x9d, 0x63, 0x72, 0x1b, 0xf8, 0x48, 0x9e, 0x83, 0x9b, 0xfd, 0x69, 0xd2,
	0x55, 0x7f, 0x32, 0xbd, 0xc3, 0x1a, 0xc1, 0xb6, 0xef, 0x9e, 0x40, 0x4b, 0x23, 0xe4, 0xff, 0xe5,
	0x79, 0x6a, 0x42, 0xd6, 0x5c, 0x72, 0x06, 0x9e, 0x31, 0x3e, 0x52, 0x4b, 0xb4, 0xfd, 0x70, 0xcd,
	0x35, 0xcf, 0xa0, 0x31, 0xe6, 0xe4, 0xbf, 0x15, 0x26, 0xb1, 0xb6, 0x86, 0x96, 0xd6, 0xce, 0xc2,
	0x0f, 0xa9, 0x8e, 0xfa, 0xc2, 0x25, 0x96, 0xdc, 0x1e, 0x39, 0x2f, 0xbb, 0x17, 0xd6, 0xb7, 0xc9,
	0xb4, 0xa5, 0x3e, 0x58, 0x1e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xed, 0x67, 0x70, 0xc6,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	//Out method for queueing massages as requested
	Out(ctx context.Context, in *MessageOut, opts ...grpc.CallOption) (*StatusResponse, error)
	//CommunicationStatus request to determine if notification is prepared or released
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	//QueueRelease method for releasing queued massages and returns if notification status if released
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	//In method is for client request for particular notification respones from system
	In(ctx context.Context, in *MessageIn, opts ...grpc.CallOption) (*StatusResponse, error)
	//Search method is for client request for particular notification details from system
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (NotificationService_SearchClient, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) Out(ctx context.Context, in *MessageOut, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/Out", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) In(ctx context.Context, in *MessageIn, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/In", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (NotificationService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NotificationService_serviceDesc.Streams[0], "/notification.NotificationService/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationServiceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NotificationService_SearchClient interface {
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type notificationServiceSearchClient struct {
	grpc.ClientStream
}

func (x *notificationServiceSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	//Out method for queueing massages as requested
	Out(context.Context, *MessageOut) (*StatusResponse, error)
	//CommunicationStatus request to determine if notification is prepared or released
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	//QueueRelease method for releasing queued massages and returns if notification status if released
	Release(context.Context, *ReleaseRequest) (*StatusResponse, error)
	//In method is for client request for particular notification respones from system
	In(context.Context, *MessageIn) (*StatusResponse, error)
	//Search method is for client request for particular notification details from system
	Search(*SearchRequest, NotificationService_SearchServer) error
}

// UnimplementedNotificationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (*UnimplementedNotificationServiceServer) Out(ctx context.Context, req *MessageOut) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Out not implemented")
}
func (*UnimplementedNotificationServiceServer) Status(ctx context.Context, req *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedNotificationServiceServer) Release(ctx context.Context, req *ReleaseRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (*UnimplementedNotificationServiceServer) In(ctx context.Context, req *MessageIn) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method In not implemented")
}
func (*UnimplementedNotificationServiceServer) Search(req *SearchRequest, srv NotificationService_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_Out_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageOut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Out(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/Out",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Out(ctx, req.(*MessageOut))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_In_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).In(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/In",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).In(ctx, req.(*MessageIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationServiceServer).Search(m, &notificationServiceSearchServer{stream})
}

type NotificationService_SearchServer interface {
	Send(*SearchResponse) error
	grpc.ServerStream
}

type notificationServiceSearchServer struct {
	grpc.ServerStream
}

func (x *notificationServiceSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Out",
			Handler:    _NotificationService_Out_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _NotificationService_Status_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _NotificationService_Release_Handler,
		},
		{
			MethodName: "In",
			Handler:    _NotificationService_In_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _NotificationService_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notification.proto",
}
